# Generated by Django 4.2.8 on 2026-01-26 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_sku_fe2039_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_barcode_d008ac_idx',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='updated_date',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity_in_stock',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_counted_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_restock_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_reserved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inventory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
