# Generated by Django 4.2.8 on 2026-01-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_barcode_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
