# Generated by Django 4.2.8 on 2026-01-27 05:40

from django.db import migrations, models


def dedupe_barcodes(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    db_alias = schema_editor.connection.alias
    seen = set()
    for product in Product.objects.using(db_alias).exclude(barcode__isnull=True).exclude(barcode="").order_by("id"):
        barcode = product.barcode.strip()
        if barcode not in seen:
            seen.add(barcode)
            if barcode != product.barcode:
                product.barcode = barcode
                product.save(update_fields=["barcode"], using=db_alias)
            continue
        counter = 1
        while True:
            candidate = f"{barcode}({counter})"
            if candidate not in seen and not Product.objects.using(db_alias).filter(barcode=candidate).exists():
                product.barcode = candidate
                product.save(update_fields=["barcode"], using=db_alias)
                seen.add(candidate)
                break
            counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_product_barcode"),
    ]

    operations = [
        migrations.RunPython(dedupe_barcodes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
