# Generated by Django 4.2.8 on 2026-01-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_items',
            new_name='number_of_transactions',
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterModelTable(
            name='dailyreport',
            table=None,
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='cash_sales',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='credit_sales',
        ),
    ]
