# Generated by Django 4.2.8 on 2026-01-26 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter valid Nepal mobile number (+977 format)",
                                regex="^\\+?977?9\\d{8,9}$",
                            )
                        ],
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=50)),
                (
                    "total_credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["customer_name"],
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="customers_phone_n_7d2329_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("payment", "Payment Received"),
                            ("adjustment", "Credit Adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "credit_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
