# Generated by Django 4.2.8 on 2026-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrregularCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "irregular_customers",
                "ordering": ["-created_date"],
            },
        ),
    ]
