# Generated by Django 4.2.8 on 2026-01-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_number", models.CharField(max_length=50, unique=True)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("credit", "Credit"),
                            ("cheque", "Cheque"),
                            ("momo", "Mobile Money"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_printed", models.BooleanField(default=False)),
                (
                    "cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sale_items",
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["sale_number"], name="sales_sale_nu_ee8c51_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["sale_date"], name="sales_sale_da_0f99d4_idx"),
        ),
    ]
