# Generated by Django 4.2.8 on 2026-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_irregular_customer_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
