# Generated by Django 4.2.8 on 2026-01-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
