# Generated by Django 4.2.8 on 2026-01-26 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customercontact_remove_credittransaction_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_nu_ee8c51_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_da_0f99d4_idx',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='line_total',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_printed',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('check', 'Check'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table=None,
        ),
    ]
