# Generated by Django 4.2.8 on 2026-01-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_irregularcustomer"),
        ("sales", "0002_sale_receipt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="irregular_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="customers.irregularcustomer",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "QR"),
                    ("credit", "Credit"),
                    ("cheque", "Cheque"),
                    ("momo", "Mobile Money"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
